global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Alertmanager configuration
# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
    - "alert_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['prometheus:9090']
    
  - job_name: 'cadvisor'
    static_configs:
    - targets: ['cadvisor:8080']

  - job_name: 'node-exporter'
    static_configs:
    - targets: ['node-exporter:9100']

  - job_name: "blackbox-icmp"
    scrape_interval: 5s
    metrics_path: /probe
    params:
      module: [icmp]
    static_configs:
      - targets: [office365.com]
        labels:
          branch: "office365"
          ###
      - targets: [semana.com]
        labels:
          branch: "semana.com"
          ###
      - targets: [74.6.143.25]
        labels:
          branch: "yahoo.com"
          ###
      - targets: [52.123.247.31]
        labels:
          branch: "teams.office.com"
          ###
      - targets: [192.168.1.254]
        labels:
          branch: "Puerta de Enlace Casa"
          ###
      - targets: [192.168.1.65]
        labels:
          branch: "Portatil"
          ###
      - targets: [8.8.8.8]
        labels:
          branch: "Google"
          ###
      - targets: [1.1.1.1]
        labels:
          branch: "1.1.1.1"
          ###
      - targets: [8.8.1.1]
        labels:
          branch: "8.8.1.1"
          ###
      - targets: [163.116.226.35]
        labels:
          branch: "163.116.226.35_Netskope"
          ###
      #- targets: [192.168.1.3]
        #labels:
          #branch: "celjey"
          ###
      - targets: [52.129.99.253]
        labels:
          branch: "52.129.99.253 Genesys 1 Casa"
          ###
      - targets: [52.129.99.254]
        labels:
          branch: "52.129.99.254 Genesys 2 Casa"
          ###
      - targets: [52.129.99.255]
        labels:
          branch: "52.129.99.255 Genesys 3 Casa"
          ###

    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115 # The blackbox exporter's real hostname:port.
        
  - job_name: 'blackbox_exporter'  # collect blackbox exporter's operational metrics.
    static_configs:
      - targets: ['blackbox:9115']