apiVersion: v1
kind: Service
metadata:
  name: alert-listener
  namespace: monitoring
spec:
  selector:
    app: alert-listener
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP